services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  chat-gateway-service:
    build:
      context: ./Chat-Gateway-Service
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    depends_on:
      - kafka
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped

  message-service:
    build:
      context: ./Message-Service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - kafka
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped

  presence-service:
    build:
      context: ./Presence-service
      dockerfile: Dockerfile
    ports:
      - "2323:2323"
    depends_on:
      - kafka
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped

  chat-room-service:
    build:
      context: ./chat-room-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - kafka
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
